version: "2"
services:
  mongo:
    image: mongo:3.4.2
    volumes:
      - wt:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    volumes:
      - .:/src
      - ../frontend:/src/public
    ports:
      - "80:3000"
      - "9229:9229"
volumes:
  wt: